// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebEngineering.Data;

#nullable disable

namespace WebEngineering.Migrations
{
    [DbContext(typeof(IdentityContext))]
    partial class IdentityContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WebEngineering.Areas.Identity.Data.Manager", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("WebEngineering.Models.Bestellung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Menge")
                        .HasColumnType("int");

                    b.Property<int>("ProduktId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProduktId");

                    b.ToTable("Bestellungen");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Date = new DateTime(2023, 2, 19, 13, 26, 0, 0, DateTimeKind.Unspecified),
                            Menge = 71,
                            ProduktId = -1
                        },
                        new
                        {
                            Id = -2,
                            Date = new DateTime(2023, 1, 12, 9, 53, 0, 0, DateTimeKind.Unspecified),
                            Menge = 184,
                            ProduktId = -2
                        },
                        new
                        {
                            Id = -3,
                            Date = new DateTime(2022, 2, 1, 20, 29, 0, 0, DateTimeKind.Unspecified),
                            Menge = 270,
                            ProduktId = -3
                        },
                        new
                        {
                            Id = -4,
                            Date = new DateTime(2022, 12, 23, 16, 51, 0, 0, DateTimeKind.Unspecified),
                            Menge = 175,
                            ProduktId = -4
                        },
                        new
                        {
                            Id = -5,
                            Date = new DateTime(2023, 12, 2, 23, 53, 0, 0, DateTimeKind.Unspecified),
                            Menge = 51,
                            ProduktId = -5
                        },
                        new
                        {
                            Id = -6,
                            Date = new DateTime(2023, 8, 23, 15, 9, 0, 0, DateTimeKind.Unspecified),
                            Menge = 189,
                            ProduktId = -6
                        },
                        new
                        {
                            Id = -7,
                            Date = new DateTime(2022, 3, 20, 4, 58, 0, 0, DateTimeKind.Unspecified),
                            Menge = 9,
                            ProduktId = -7
                        },
                        new
                        {
                            Id = -8,
                            Date = new DateTime(2023, 9, 23, 16, 3, 0, 0, DateTimeKind.Unspecified),
                            Menge = 83,
                            ProduktId = -8
                        },
                        new
                        {
                            Id = -9,
                            Date = new DateTime(2022, 6, 18, 9, 54, 0, 0, DateTimeKind.Unspecified),
                            Menge = 26,
                            ProduktId = -9
                        },
                        new
                        {
                            Id = -10,
                            Date = new DateTime(2022, 1, 8, 5, 0, 0, 0, DateTimeKind.Unspecified),
                            Menge = 110,
                            ProduktId = -10
                        },
                        new
                        {
                            Id = -11,
                            Date = new DateTime(2023, 1, 1, 17, 42, 0, 0, DateTimeKind.Unspecified),
                            Menge = 194,
                            ProduktId = -11
                        },
                        new
                        {
                            Id = -12,
                            Date = new DateTime(2022, 11, 13, 23, 36, 0, 0, DateTimeKind.Unspecified),
                            Menge = 234,
                            ProduktId = -12
                        },
                        new
                        {
                            Id = -13,
                            Date = new DateTime(2022, 1, 11, 22, 32, 0, 0, DateTimeKind.Unspecified),
                            Menge = 237,
                            ProduktId = -13
                        },
                        new
                        {
                            Id = -14,
                            Date = new DateTime(2022, 3, 29, 6, 29, 0, 0, DateTimeKind.Unspecified),
                            Menge = 277,
                            ProduktId = -14
                        },
                        new
                        {
                            Id = -15,
                            Date = new DateTime(2023, 11, 3, 6, 50, 0, 0, DateTimeKind.Unspecified),
                            Menge = 150,
                            ProduktId = -15
                        },
                        new
                        {
                            Id = -16,
                            Date = new DateTime(2023, 8, 2, 2, 26, 0, 0, DateTimeKind.Unspecified),
                            Menge = 11,
                            ProduktId = -16
                        },
                        new
                        {
                            Id = -17,
                            Date = new DateTime(2022, 1, 24, 20, 3, 0, 0, DateTimeKind.Unspecified),
                            Menge = 260,
                            ProduktId = -17
                        },
                        new
                        {
                            Id = -18,
                            Date = new DateTime(2023, 10, 18, 11, 26, 0, 0, DateTimeKind.Unspecified),
                            Menge = 97,
                            ProduktId = -18
                        },
                        new
                        {
                            Id = -19,
                            Date = new DateTime(2022, 8, 17, 16, 18, 0, 0, DateTimeKind.Unspecified),
                            Menge = 237,
                            ProduktId = -19
                        },
                        new
                        {
                            Id = -20,
                            Date = new DateTime(2023, 3, 30, 13, 29, 0, 0, DateTimeKind.Unspecified),
                            Menge = 229,
                            ProduktId = -20
                        },
                        new
                        {
                            Id = -21,
                            Date = new DateTime(2022, 6, 12, 23, 20, 0, 0, DateTimeKind.Unspecified),
                            Menge = 227,
                            ProduktId = -21
                        },
                        new
                        {
                            Id = -22,
                            Date = new DateTime(2023, 11, 13, 7, 48, 0, 0, DateTimeKind.Unspecified),
                            Menge = 48,
                            ProduktId = -22
                        },
                        new
                        {
                            Id = -23,
                            Date = new DateTime(2022, 1, 26, 17, 26, 0, 0, DateTimeKind.Unspecified),
                            Menge = 161,
                            ProduktId = -23
                        },
                        new
                        {
                            Id = -24,
                            Date = new DateTime(2023, 4, 20, 11, 54, 0, 0, DateTimeKind.Unspecified),
                            Menge = 189,
                            ProduktId = -24
                        },
                        new
                        {
                            Id = -25,
                            Date = new DateTime(2022, 3, 8, 7, 36, 0, 0, DateTimeKind.Unspecified),
                            Menge = 63,
                            ProduktId = -25
                        },
                        new
                        {
                            Id = -26,
                            Date = new DateTime(2023, 12, 28, 22, 15, 0, 0, DateTimeKind.Unspecified),
                            Menge = 16,
                            ProduktId = -26
                        },
                        new
                        {
                            Id = -27,
                            Date = new DateTime(2022, 1, 15, 8, 40, 0, 0, DateTimeKind.Unspecified),
                            Menge = 87,
                            ProduktId = -27
                        },
                        new
                        {
                            Id = -28,
                            Date = new DateTime(2022, 11, 17, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            Menge = 98,
                            ProduktId = -28
                        },
                        new
                        {
                            Id = -29,
                            Date = new DateTime(2022, 2, 23, 10, 41, 0, 0, DateTimeKind.Unspecified),
                            Menge = 52,
                            ProduktId = -29
                        },
                        new
                        {
                            Id = -30,
                            Date = new DateTime(2022, 7, 13, 11, 34, 0, 0, DateTimeKind.Unspecified),
                            Menge = 119,
                            ProduktId = -30
                        },
                        new
                        {
                            Id = -31,
                            Date = new DateTime(2023, 10, 8, 17, 56, 0, 0, DateTimeKind.Unspecified),
                            Menge = 136,
                            ProduktId = -31
                        },
                        new
                        {
                            Id = -32,
                            Date = new DateTime(2023, 4, 15, 14, 22, 0, 0, DateTimeKind.Unspecified),
                            Menge = 108,
                            ProduktId = -32
                        },
                        new
                        {
                            Id = -33,
                            Date = new DateTime(2023, 5, 15, 22, 51, 0, 0, DateTimeKind.Unspecified),
                            Menge = 202,
                            ProduktId = -33
                        },
                        new
                        {
                            Id = -34,
                            Date = new DateTime(2023, 4, 10, 0, 13, 0, 0, DateTimeKind.Unspecified),
                            Menge = 278,
                            ProduktId = -34
                        },
                        new
                        {
                            Id = -35,
                            Date = new DateTime(2022, 11, 17, 18, 48, 0, 0, DateTimeKind.Unspecified),
                            Menge = 140,
                            ProduktId = -35
                        },
                        new
                        {
                            Id = -36,
                            Date = new DateTime(2023, 10, 28, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Menge = 154,
                            ProduktId = -36
                        },
                        new
                        {
                            Id = -37,
                            Date = new DateTime(2022, 3, 25, 6, 12, 0, 0, DateTimeKind.Unspecified),
                            Menge = 29,
                            ProduktId = -37
                        },
                        new
                        {
                            Id = -38,
                            Date = new DateTime(2022, 8, 22, 12, 46, 0, 0, DateTimeKind.Unspecified),
                            Menge = 276,
                            ProduktId = -38
                        },
                        new
                        {
                            Id = -39,
                            Date = new DateTime(2022, 11, 5, 5, 38, 0, 0, DateTimeKind.Unspecified),
                            Menge = 248,
                            ProduktId = -39
                        },
                        new
                        {
                            Id = -40,
                            Date = new DateTime(2023, 6, 15, 15, 13, 0, 0, DateTimeKind.Unspecified),
                            Menge = 192,
                            ProduktId = -40
                        },
                        new
                        {
                            Id = -41,
                            Date = new DateTime(2022, 2, 20, 18, 40, 0, 0, DateTimeKind.Unspecified),
                            Menge = 99,
                            ProduktId = -41
                        },
                        new
                        {
                            Id = -42,
                            Date = new DateTime(2022, 2, 21, 8, 48, 0, 0, DateTimeKind.Unspecified),
                            Menge = 235,
                            ProduktId = -42
                        },
                        new
                        {
                            Id = -43,
                            Date = new DateTime(2022, 1, 31, 18, 20, 0, 0, DateTimeKind.Unspecified),
                            Menge = 73,
                            ProduktId = -43
                        },
                        new
                        {
                            Id = -44,
                            Date = new DateTime(2023, 9, 19, 20, 38, 0, 0, DateTimeKind.Unspecified),
                            Menge = 258,
                            ProduktId = -44
                        },
                        new
                        {
                            Id = -45,
                            Date = new DateTime(2023, 3, 28, 10, 7, 0, 0, DateTimeKind.Unspecified),
                            Menge = 79,
                            ProduktId = -45
                        },
                        new
                        {
                            Id = -46,
                            Date = new DateTime(2023, 1, 14, 22, 14, 0, 0, DateTimeKind.Unspecified),
                            Menge = 220,
                            ProduktId = -46
                        },
                        new
                        {
                            Id = -47,
                            Date = new DateTime(2022, 1, 8, 8, 18, 0, 0, DateTimeKind.Unspecified),
                            Menge = 257,
                            ProduktId = -47
                        },
                        new
                        {
                            Id = -48,
                            Date = new DateTime(2022, 9, 22, 2, 12, 0, 0, DateTimeKind.Unspecified),
                            Menge = 277,
                            ProduktId = -48
                        },
                        new
                        {
                            Id = -49,
                            Date = new DateTime(2023, 6, 17, 4, 13, 0, 0, DateTimeKind.Unspecified),
                            Menge = 206,
                            ProduktId = -49
                        },
                        new
                        {
                            Id = -50,
                            Date = new DateTime(2022, 4, 2, 7, 19, 0, 0, DateTimeKind.Unspecified),
                            Menge = 141,
                            ProduktId = -50
                        },
                        new
                        {
                            Id = -51,
                            Date = new DateTime(2022, 1, 24, 17, 58, 0, 0, DateTimeKind.Unspecified),
                            Menge = 264,
                            ProduktId = -51
                        },
                        new
                        {
                            Id = -52,
                            Date = new DateTime(2023, 3, 23, 4, 42, 0, 0, DateTimeKind.Unspecified),
                            Menge = 121,
                            ProduktId = -52
                        },
                        new
                        {
                            Id = -53,
                            Date = new DateTime(2022, 7, 12, 11, 21, 0, 0, DateTimeKind.Unspecified),
                            Menge = 143,
                            ProduktId = -53
                        },
                        new
                        {
                            Id = -54,
                            Date = new DateTime(2023, 6, 4, 22, 52, 0, 0, DateTimeKind.Unspecified),
                            Menge = 148,
                            ProduktId = -54
                        },
                        new
                        {
                            Id = -55,
                            Date = new DateTime(2023, 1, 21, 13, 18, 0, 0, DateTimeKind.Unspecified),
                            Menge = 7,
                            ProduktId = -55
                        },
                        new
                        {
                            Id = -56,
                            Date = new DateTime(2022, 5, 22, 21, 52, 0, 0, DateTimeKind.Unspecified),
                            Menge = 141,
                            ProduktId = -56
                        },
                        new
                        {
                            Id = -57,
                            Date = new DateTime(2023, 8, 27, 20, 40, 0, 0, DateTimeKind.Unspecified),
                            Menge = 296,
                            ProduktId = -57
                        },
                        new
                        {
                            Id = -58,
                            Date = new DateTime(2023, 6, 27, 3, 29, 0, 0, DateTimeKind.Unspecified),
                            Menge = 82,
                            ProduktId = -58
                        },
                        new
                        {
                            Id = -59,
                            Date = new DateTime(2022, 8, 15, 20, 49, 0, 0, DateTimeKind.Unspecified),
                            Menge = 30,
                            ProduktId = -59
                        },
                        new
                        {
                            Id = -60,
                            Date = new DateTime(2023, 3, 22, 8, 2, 0, 0, DateTimeKind.Unspecified),
                            Menge = 69,
                            ProduktId = -60
                        },
                        new
                        {
                            Id = -61,
                            Date = new DateTime(2023, 11, 17, 17, 17, 0, 0, DateTimeKind.Unspecified),
                            Menge = 71,
                            ProduktId = -61
                        },
                        new
                        {
                            Id = -62,
                            Date = new DateTime(2023, 11, 2, 3, 20, 0, 0, DateTimeKind.Unspecified),
                            Menge = 89,
                            ProduktId = -62
                        },
                        new
                        {
                            Id = -63,
                            Date = new DateTime(2022, 3, 1, 7, 6, 0, 0, DateTimeKind.Unspecified),
                            Menge = 76,
                            ProduktId = -63
                        },
                        new
                        {
                            Id = -64,
                            Date = new DateTime(2023, 10, 22, 13, 15, 0, 0, DateTimeKind.Unspecified),
                            Menge = 22,
                            ProduktId = -64
                        },
                        new
                        {
                            Id = -65,
                            Date = new DateTime(2023, 10, 19, 6, 29, 0, 0, DateTimeKind.Unspecified),
                            Menge = 118,
                            ProduktId = -65
                        },
                        new
                        {
                            Id = -66,
                            Date = new DateTime(2022, 9, 14, 19, 16, 0, 0, DateTimeKind.Unspecified),
                            Menge = 172,
                            ProduktId = -66
                        },
                        new
                        {
                            Id = -67,
                            Date = new DateTime(2022, 3, 26, 15, 4, 0, 0, DateTimeKind.Unspecified),
                            Menge = 147,
                            ProduktId = -67
                        },
                        new
                        {
                            Id = -68,
                            Date = new DateTime(2022, 4, 23, 20, 3, 0, 0, DateTimeKind.Unspecified),
                            Menge = 260,
                            ProduktId = -68
                        },
                        new
                        {
                            Id = -69,
                            Date = new DateTime(2023, 2, 18, 19, 13, 0, 0, DateTimeKind.Unspecified),
                            Menge = 19,
                            ProduktId = -69
                        },
                        new
                        {
                            Id = -70,
                            Date = new DateTime(2022, 9, 27, 18, 15, 0, 0, DateTimeKind.Unspecified),
                            Menge = 270,
                            ProduktId = -70
                        },
                        new
                        {
                            Id = -71,
                            Date = new DateTime(2022, 12, 25, 13, 14, 0, 0, DateTimeKind.Unspecified),
                            Menge = 137,
                            ProduktId = -71
                        },
                        new
                        {
                            Id = -72,
                            Date = new DateTime(2022, 3, 27, 11, 50, 0, 0, DateTimeKind.Unspecified),
                            Menge = 16,
                            ProduktId = -72
                        },
                        new
                        {
                            Id = -73,
                            Date = new DateTime(2022, 10, 21, 11, 19, 0, 0, DateTimeKind.Unspecified),
                            Menge = 139,
                            ProduktId = -73
                        },
                        new
                        {
                            Id = -74,
                            Date = new DateTime(2022, 3, 29, 10, 3, 0, 0, DateTimeKind.Unspecified),
                            Menge = 85,
                            ProduktId = -74
                        },
                        new
                        {
                            Id = -75,
                            Date = new DateTime(2022, 3, 22, 19, 9, 0, 0, DateTimeKind.Unspecified),
                            Menge = 234,
                            ProduktId = -75
                        },
                        new
                        {
                            Id = -76,
                            Date = new DateTime(2022, 8, 22, 16, 10, 0, 0, DateTimeKind.Unspecified),
                            Menge = 281,
                            ProduktId = -76
                        },
                        new
                        {
                            Id = -77,
                            Date = new DateTime(2022, 3, 16, 4, 15, 0, 0, DateTimeKind.Unspecified),
                            Menge = 259,
                            ProduktId = -77
                        },
                        new
                        {
                            Id = -78,
                            Date = new DateTime(2023, 8, 15, 20, 57, 0, 0, DateTimeKind.Unspecified),
                            Menge = 222,
                            ProduktId = -78
                        },
                        new
                        {
                            Id = -79,
                            Date = new DateTime(2022, 5, 8, 20, 23, 0, 0, DateTimeKind.Unspecified),
                            Menge = 194,
                            ProduktId = -79
                        },
                        new
                        {
                            Id = -80,
                            Date = new DateTime(2022, 9, 20, 23, 35, 0, 0, DateTimeKind.Unspecified),
                            Menge = 108,
                            ProduktId = -80
                        });
                });

            modelBuilder.Entity("WebEngineering.Models.Lieferung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BestellungId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Menge")
                        .HasColumnType("int");

                    b.Property<int>("ProduktId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BestellungId");

                    b.HasIndex("ProduktId");

                    b.ToTable("Lieferungen");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            BestellungId = -1,
                            Date = new DateTime(2023, 3, 5, 13, 26, 0, 0, DateTimeKind.Unspecified),
                            Menge = 71,
                            ProduktId = -1
                        },
                        new
                        {
                            Id = -2,
                            BestellungId = -2,
                            Date = new DateTime(2023, 1, 26, 9, 53, 0, 0, DateTimeKind.Unspecified),
                            Menge = 184,
                            ProduktId = -2
                        },
                        new
                        {
                            Id = -3,
                            BestellungId = -3,
                            Date = new DateTime(2022, 2, 8, 20, 29, 0, 0, DateTimeKind.Unspecified),
                            Menge = 270,
                            ProduktId = -3
                        },
                        new
                        {
                            Id = -4,
                            BestellungId = -4,
                            Date = new DateTime(2023, 1, 6, 16, 51, 0, 0, DateTimeKind.Unspecified),
                            Menge = 175,
                            ProduktId = -4
                        },
                        new
                        {
                            Id = -5,
                            BestellungId = -5,
                            Date = new DateTime(2023, 12, 9, 23, 53, 0, 0, DateTimeKind.Unspecified),
                            Menge = 51,
                            ProduktId = -5
                        },
                        new
                        {
                            Id = -6,
                            BestellungId = -6,
                            Date = new DateTime(2023, 8, 30, 15, 9, 0, 0, DateTimeKind.Unspecified),
                            Menge = 189,
                            ProduktId = -6
                        },
                        new
                        {
                            Id = -7,
                            BestellungId = -7,
                            Date = new DateTime(2022, 4, 3, 4, 58, 0, 0, DateTimeKind.Unspecified),
                            Menge = 9,
                            ProduktId = -7
                        },
                        new
                        {
                            Id = -8,
                            BestellungId = -8,
                            Date = new DateTime(2023, 10, 7, 16, 3, 0, 0, DateTimeKind.Unspecified),
                            Menge = 83,
                            ProduktId = -8
                        },
                        new
                        {
                            Id = -9,
                            BestellungId = -9,
                            Date = new DateTime(2022, 6, 25, 9, 54, 0, 0, DateTimeKind.Unspecified),
                            Menge = 26,
                            ProduktId = -9
                        },
                        new
                        {
                            Id = -10,
                            BestellungId = -10,
                            Date = new DateTime(2022, 1, 15, 5, 0, 0, 0, DateTimeKind.Unspecified),
                            Menge = 110,
                            ProduktId = -10
                        },
                        new
                        {
                            Id = -11,
                            BestellungId = -11,
                            Date = new DateTime(2023, 1, 15, 17, 42, 0, 0, DateTimeKind.Unspecified),
                            Menge = 194,
                            ProduktId = -11
                        },
                        new
                        {
                            Id = -12,
                            BestellungId = -12,
                            Date = new DateTime(2022, 11, 27, 23, 36, 0, 0, DateTimeKind.Unspecified),
                            Menge = 234,
                            ProduktId = -12
                        },
                        new
                        {
                            Id = -13,
                            BestellungId = -13,
                            Date = new DateTime(2022, 1, 25, 22, 32, 0, 0, DateTimeKind.Unspecified),
                            Menge = 237,
                            ProduktId = -13
                        },
                        new
                        {
                            Id = -14,
                            BestellungId = -14,
                            Date = new DateTime(2022, 4, 12, 6, 29, 0, 0, DateTimeKind.Unspecified),
                            Menge = 277,
                            ProduktId = -14
                        },
                        new
                        {
                            Id = -15,
                            BestellungId = -15,
                            Date = new DateTime(2023, 11, 17, 6, 50, 0, 0, DateTimeKind.Unspecified),
                            Menge = 150,
                            ProduktId = -15
                        },
                        new
                        {
                            Id = -16,
                            BestellungId = -16,
                            Date = new DateTime(2023, 8, 16, 2, 26, 0, 0, DateTimeKind.Unspecified),
                            Menge = 11,
                            ProduktId = -16
                        },
                        new
                        {
                            Id = -17,
                            BestellungId = -17,
                            Date = new DateTime(2022, 2, 7, 20, 3, 0, 0, DateTimeKind.Unspecified),
                            Menge = 260,
                            ProduktId = -17
                        },
                        new
                        {
                            Id = -18,
                            BestellungId = -18,
                            Date = new DateTime(2023, 10, 25, 11, 26, 0, 0, DateTimeKind.Unspecified),
                            Menge = 97,
                            ProduktId = -18
                        },
                        new
                        {
                            Id = -19,
                            BestellungId = -19,
                            Date = new DateTime(2022, 8, 31, 16, 18, 0, 0, DateTimeKind.Unspecified),
                            Menge = 237,
                            ProduktId = -19
                        },
                        new
                        {
                            Id = -20,
                            BestellungId = -20,
                            Date = new DateTime(2023, 4, 13, 13, 29, 0, 0, DateTimeKind.Unspecified),
                            Menge = 229,
                            ProduktId = -20
                        },
                        new
                        {
                            Id = -21,
                            BestellungId = -21,
                            Date = new DateTime(2022, 6, 19, 23, 20, 0, 0, DateTimeKind.Unspecified),
                            Menge = 227,
                            ProduktId = -21
                        },
                        new
                        {
                            Id = -22,
                            BestellungId = -22,
                            Date = new DateTime(2023, 11, 27, 7, 48, 0, 0, DateTimeKind.Unspecified),
                            Menge = 48,
                            ProduktId = -22
                        },
                        new
                        {
                            Id = -23,
                            BestellungId = -23,
                            Date = new DateTime(2022, 2, 9, 17, 26, 0, 0, DateTimeKind.Unspecified),
                            Menge = 161,
                            ProduktId = -23
                        },
                        new
                        {
                            Id = -24,
                            BestellungId = -24,
                            Date = new DateTime(2023, 4, 27, 11, 54, 0, 0, DateTimeKind.Unspecified),
                            Menge = 189,
                            ProduktId = -24
                        },
                        new
                        {
                            Id = -25,
                            BestellungId = -25,
                            Date = new DateTime(2022, 3, 22, 7, 36, 0, 0, DateTimeKind.Unspecified),
                            Menge = 63,
                            ProduktId = -25
                        },
                        new
                        {
                            Id = -26,
                            BestellungId = -26,
                            Date = new DateTime(2024, 1, 4, 22, 15, 0, 0, DateTimeKind.Unspecified),
                            Menge = 16,
                            ProduktId = -26
                        },
                        new
                        {
                            Id = -27,
                            BestellungId = -27,
                            Date = new DateTime(2022, 1, 22, 8, 40, 0, 0, DateTimeKind.Unspecified),
                            Menge = 87,
                            ProduktId = -27
                        },
                        new
                        {
                            Id = -28,
                            BestellungId = -28,
                            Date = new DateTime(2022, 12, 1, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            Menge = 98,
                            ProduktId = -28
                        },
                        new
                        {
                            Id = -29,
                            BestellungId = -29,
                            Date = new DateTime(2022, 3, 2, 10, 41, 0, 0, DateTimeKind.Unspecified),
                            Menge = 52,
                            ProduktId = -29
                        },
                        new
                        {
                            Id = -30,
                            BestellungId = -30,
                            Date = new DateTime(2022, 7, 20, 11, 34, 0, 0, DateTimeKind.Unspecified),
                            Menge = 119,
                            ProduktId = -30
                        },
                        new
                        {
                            Id = -31,
                            BestellungId = -31,
                            Date = new DateTime(2023, 10, 15, 17, 56, 0, 0, DateTimeKind.Unspecified),
                            Menge = 136,
                            ProduktId = -31
                        },
                        new
                        {
                            Id = -32,
                            BestellungId = -32,
                            Date = new DateTime(2023, 4, 29, 14, 22, 0, 0, DateTimeKind.Unspecified),
                            Menge = 108,
                            ProduktId = -32
                        },
                        new
                        {
                            Id = -33,
                            BestellungId = -33,
                            Date = new DateTime(2023, 5, 29, 22, 51, 0, 0, DateTimeKind.Unspecified),
                            Menge = 202,
                            ProduktId = -33
                        },
                        new
                        {
                            Id = -34,
                            BestellungId = -34,
                            Date = new DateTime(2023, 4, 24, 0, 13, 0, 0, DateTimeKind.Unspecified),
                            Menge = 278,
                            ProduktId = -34
                        },
                        new
                        {
                            Id = -35,
                            BestellungId = -35,
                            Date = new DateTime(2022, 12, 1, 18, 48, 0, 0, DateTimeKind.Unspecified),
                            Menge = 140,
                            ProduktId = -35
                        },
                        new
                        {
                            Id = -36,
                            BestellungId = -36,
                            Date = new DateTime(2023, 11, 11, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Menge = 154,
                            ProduktId = -36
                        },
                        new
                        {
                            Id = -37,
                            BestellungId = -37,
                            Date = new DateTime(2022, 4, 1, 6, 12, 0, 0, DateTimeKind.Unspecified),
                            Menge = 29,
                            ProduktId = -37
                        },
                        new
                        {
                            Id = -38,
                            BestellungId = -38,
                            Date = new DateTime(2022, 8, 29, 12, 46, 0, 0, DateTimeKind.Unspecified),
                            Menge = 276,
                            ProduktId = -38
                        },
                        new
                        {
                            Id = -39,
                            BestellungId = -39,
                            Date = new DateTime(2022, 11, 19, 5, 38, 0, 0, DateTimeKind.Unspecified),
                            Menge = 248,
                            ProduktId = -39
                        },
                        new
                        {
                            Id = -40,
                            BestellungId = -40,
                            Date = new DateTime(2023, 6, 29, 15, 13, 0, 0, DateTimeKind.Unspecified),
                            Menge = 192,
                            ProduktId = -40
                        },
                        new
                        {
                            Id = -41,
                            BestellungId = -41,
                            Date = new DateTime(2022, 3, 6, 18, 40, 0, 0, DateTimeKind.Unspecified),
                            Menge = 99,
                            ProduktId = -41
                        },
                        new
                        {
                            Id = -42,
                            BestellungId = -42,
                            Date = new DateTime(2022, 2, 28, 8, 48, 0, 0, DateTimeKind.Unspecified),
                            Menge = 235,
                            ProduktId = -42
                        },
                        new
                        {
                            Id = -43,
                            BestellungId = -43,
                            Date = new DateTime(2022, 2, 14, 18, 20, 0, 0, DateTimeKind.Unspecified),
                            Menge = 73,
                            ProduktId = -43
                        },
                        new
                        {
                            Id = -44,
                            BestellungId = -44,
                            Date = new DateTime(2023, 10, 3, 20, 38, 0, 0, DateTimeKind.Unspecified),
                            Menge = 258,
                            ProduktId = -44
                        },
                        new
                        {
                            Id = -45,
                            BestellungId = -45,
                            Date = new DateTime(2023, 4, 4, 10, 7, 0, 0, DateTimeKind.Unspecified),
                            Menge = 79,
                            ProduktId = -45
                        },
                        new
                        {
                            Id = -46,
                            BestellungId = -46,
                            Date = new DateTime(2023, 1, 28, 22, 14, 0, 0, DateTimeKind.Unspecified),
                            Menge = 220,
                            ProduktId = -46
                        },
                        new
                        {
                            Id = -47,
                            BestellungId = -47,
                            Date = new DateTime(2022, 1, 15, 8, 18, 0, 0, DateTimeKind.Unspecified),
                            Menge = 257,
                            ProduktId = -47
                        },
                        new
                        {
                            Id = -48,
                            BestellungId = -48,
                            Date = new DateTime(2022, 9, 29, 2, 12, 0, 0, DateTimeKind.Unspecified),
                            Menge = 277,
                            ProduktId = -48
                        },
                        new
                        {
                            Id = -49,
                            BestellungId = -49,
                            Date = new DateTime(2023, 6, 24, 4, 13, 0, 0, DateTimeKind.Unspecified),
                            Menge = 206,
                            ProduktId = -49
                        },
                        new
                        {
                            Id = -50,
                            BestellungId = -50,
                            Date = new DateTime(2022, 4, 9, 7, 19, 0, 0, DateTimeKind.Unspecified),
                            Menge = 141,
                            ProduktId = -50
                        },
                        new
                        {
                            Id = -51,
                            BestellungId = -51,
                            Date = new DateTime(2022, 1, 31, 17, 58, 0, 0, DateTimeKind.Unspecified),
                            Menge = 264,
                            ProduktId = -51
                        },
                        new
                        {
                            Id = -52,
                            BestellungId = -52,
                            Date = new DateTime(2023, 4, 6, 4, 42, 0, 0, DateTimeKind.Unspecified),
                            Menge = 121,
                            ProduktId = -52
                        },
                        new
                        {
                            Id = -53,
                            BestellungId = -53,
                            Date = new DateTime(2022, 7, 19, 11, 21, 0, 0, DateTimeKind.Unspecified),
                            Menge = 143,
                            ProduktId = -53
                        },
                        new
                        {
                            Id = -54,
                            BestellungId = -54,
                            Date = new DateTime(2023, 6, 18, 22, 52, 0, 0, DateTimeKind.Unspecified),
                            Menge = 148,
                            ProduktId = -54
                        },
                        new
                        {
                            Id = -55,
                            BestellungId = -55,
                            Date = new DateTime(2023, 2, 4, 13, 18, 0, 0, DateTimeKind.Unspecified),
                            Menge = 7,
                            ProduktId = -55
                        },
                        new
                        {
                            Id = -56,
                            BestellungId = -56,
                            Date = new DateTime(2022, 5, 29, 21, 52, 0, 0, DateTimeKind.Unspecified),
                            Menge = 141,
                            ProduktId = -56
                        },
                        new
                        {
                            Id = -57,
                            BestellungId = -57,
                            Date = new DateTime(2023, 9, 10, 20, 40, 0, 0, DateTimeKind.Unspecified),
                            Menge = 296,
                            ProduktId = -57
                        },
                        new
                        {
                            Id = -58,
                            BestellungId = -58,
                            Date = new DateTime(2023, 7, 11, 3, 29, 0, 0, DateTimeKind.Unspecified),
                            Menge = 82,
                            ProduktId = -58
                        },
                        new
                        {
                            Id = -59,
                            BestellungId = -59,
                            Date = new DateTime(2022, 8, 29, 20, 49, 0, 0, DateTimeKind.Unspecified),
                            Menge = 30,
                            ProduktId = -59
                        },
                        new
                        {
                            Id = -60,
                            BestellungId = -60,
                            Date = new DateTime(2023, 3, 29, 8, 2, 0, 0, DateTimeKind.Unspecified),
                            Menge = 69,
                            ProduktId = -60
                        },
                        new
                        {
                            Id = -61,
                            BestellungId = -61,
                            Date = new DateTime(2023, 12, 1, 17, 17, 0, 0, DateTimeKind.Unspecified),
                            Menge = 71,
                            ProduktId = -61
                        },
                        new
                        {
                            Id = -62,
                            BestellungId = -62,
                            Date = new DateTime(2023, 11, 9, 3, 20, 0, 0, DateTimeKind.Unspecified),
                            Menge = 89,
                            ProduktId = -62
                        },
                        new
                        {
                            Id = -63,
                            BestellungId = -63,
                            Date = new DateTime(2022, 3, 15, 7, 6, 0, 0, DateTimeKind.Unspecified),
                            Menge = 76,
                            ProduktId = -63
                        },
                        new
                        {
                            Id = -64,
                            BestellungId = -64,
                            Date = new DateTime(2023, 11, 5, 13, 15, 0, 0, DateTimeKind.Unspecified),
                            Menge = 22,
                            ProduktId = -64
                        },
                        new
                        {
                            Id = -65,
                            BestellungId = -65,
                            Date = new DateTime(2023, 11, 2, 6, 29, 0, 0, DateTimeKind.Unspecified),
                            Menge = 118,
                            ProduktId = -65
                        },
                        new
                        {
                            Id = -66,
                            BestellungId = -66,
                            Date = new DateTime(2022, 9, 28, 19, 16, 0, 0, DateTimeKind.Unspecified),
                            Menge = 172,
                            ProduktId = -66
                        },
                        new
                        {
                            Id = -67,
                            BestellungId = -67,
                            Date = new DateTime(2022, 4, 9, 15, 4, 0, 0, DateTimeKind.Unspecified),
                            Menge = 147,
                            ProduktId = -67
                        },
                        new
                        {
                            Id = -68,
                            BestellungId = -68,
                            Date = new DateTime(2022, 4, 30, 20, 3, 0, 0, DateTimeKind.Unspecified),
                            Menge = 260,
                            ProduktId = -68
                        },
                        new
                        {
                            Id = -69,
                            BestellungId = -69,
                            Date = new DateTime(2023, 3, 4, 19, 13, 0, 0, DateTimeKind.Unspecified),
                            Menge = 19,
                            ProduktId = -69
                        },
                        new
                        {
                            Id = -70,
                            BestellungId = -70,
                            Date = new DateTime(2022, 10, 4, 18, 15, 0, 0, DateTimeKind.Unspecified),
                            Menge = 270,
                            ProduktId = -70
                        },
                        new
                        {
                            Id = -71,
                            BestellungId = -71,
                            Date = new DateTime(2023, 1, 8, 13, 14, 0, 0, DateTimeKind.Unspecified),
                            Menge = 137,
                            ProduktId = -71
                        },
                        new
                        {
                            Id = -72,
                            BestellungId = -72,
                            Date = new DateTime(2022, 4, 3, 11, 50, 0, 0, DateTimeKind.Unspecified),
                            Menge = 16,
                            ProduktId = -72
                        },
                        new
                        {
                            Id = -73,
                            BestellungId = -73,
                            Date = new DateTime(2022, 10, 28, 11, 19, 0, 0, DateTimeKind.Unspecified),
                            Menge = 139,
                            ProduktId = -73
                        },
                        new
                        {
                            Id = -74,
                            BestellungId = -74,
                            Date = new DateTime(2022, 4, 5, 10, 3, 0, 0, DateTimeKind.Unspecified),
                            Menge = 85,
                            ProduktId = -74
                        },
                        new
                        {
                            Id = -75,
                            BestellungId = -75,
                            Date = new DateTime(2022, 3, 29, 19, 9, 0, 0, DateTimeKind.Unspecified),
                            Menge = 234,
                            ProduktId = -75
                        },
                        new
                        {
                            Id = -76,
                            BestellungId = -76,
                            Date = new DateTime(2022, 8, 29, 16, 10, 0, 0, DateTimeKind.Unspecified),
                            Menge = 281,
                            ProduktId = -76
                        },
                        new
                        {
                            Id = -77,
                            BestellungId = -77,
                            Date = new DateTime(2022, 3, 30, 4, 15, 0, 0, DateTimeKind.Unspecified),
                            Menge = 259,
                            ProduktId = -77
                        },
                        new
                        {
                            Id = -78,
                            BestellungId = -78,
                            Date = new DateTime(2023, 8, 29, 20, 57, 0, 0, DateTimeKind.Unspecified),
                            Menge = 222,
                            ProduktId = -78
                        },
                        new
                        {
                            Id = -79,
                            BestellungId = -79,
                            Date = new DateTime(2022, 5, 15, 20, 23, 0, 0, DateTimeKind.Unspecified),
                            Menge = 194,
                            ProduktId = -79
                        },
                        new
                        {
                            Id = -80,
                            BestellungId = -80,
                            Date = new DateTime(2022, 9, 27, 23, 35, 0, 0, DateTimeKind.Unspecified),
                            Menge = 108,
                            ProduktId = -80
                        });
                });

            modelBuilder.Entity("WebEngineering.Models.Produkt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Produkte");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Name = "Steinplatten"
                        },
                        new
                        {
                            Id = -2,
                            Name = "Goldsensoren"
                        },
                        new
                        {
                            Id = -3,
                            Name = "Stahlschrauben"
                        },
                        new
                        {
                            Id = -4,
                            Name = "Papiersensoren"
                        },
                        new
                        {
                            Id = -5,
                            Name = "Stahlplatten"
                        },
                        new
                        {
                            Id = -6,
                            Name = "Metalldichtungen"
                        },
                        new
                        {
                            Id = -7,
                            Name = "Silberventile"
                        },
                        new
                        {
                            Id = -8,
                            Name = "Glasschalter"
                        },
                        new
                        {
                            Id = -9,
                            Name = "Aluminiumschalter"
                        },
                        new
                        {
                            Id = -10,
                            Name = "Keramikschrauben"
                        },
                        new
                        {
                            Id = -11,
                            Name = "Silberdichtungen"
                        },
                        new
                        {
                            Id = -12,
                            Name = "Aluminiumschrauben"
                        },
                        new
                        {
                            Id = -13,
                            Name = "Acrylunterlegscheiben"
                        },
                        new
                        {
                            Id = -14,
                            Name = "Golddichtungen"
                        },
                        new
                        {
                            Id = -15,
                            Name = "Betonschrauben"
                        },
                        new
                        {
                            Id = -16,
                            Name = "Gummiplatten"
                        },
                        new
                        {
                            Id = -17,
                            Name = "Gummipumpen"
                        },
                        new
                        {
                            Id = -18,
                            Name = "Steinfilter"
                        },
                        new
                        {
                            Id = -19,
                            Name = "Acrylunterlegscheiben"
                        },
                        new
                        {
                            Id = -20,
                            Name = "Acrylfilter"
                        },
                        new
                        {
                            Id = -21,
                            Name = "Betongehäuse"
                        },
                        new
                        {
                            Id = -22,
                            Name = "Acrylventile"
                        },
                        new
                        {
                            Id = -23,
                            Name = "Aluminiumfilter"
                        },
                        new
                        {
                            Id = -24,
                            Name = "Keramikpumpen"
                        },
                        new
                        {
                            Id = -25,
                            Name = "Keramiksensoren"
                        },
                        new
                        {
                            Id = -26,
                            Name = "Betonrohre"
                        },
                        new
                        {
                            Id = -27,
                            Name = "Betonplatten"
                        },
                        new
                        {
                            Id = -28,
                            Name = "Acrylriemen"
                        },
                        new
                        {
                            Id = -29,
                            Name = "Plexiglasventile"
                        },
                        new
                        {
                            Id = -30,
                            Name = "Textilsensoren"
                        },
                        new
                        {
                            Id = -31,
                            Name = "Betonrohre"
                        },
                        new
                        {
                            Id = -32,
                            Name = "Plexiglasbolzen"
                        },
                        new
                        {
                            Id = -33,
                            Name = "Betonpumpen"
                        },
                        new
                        {
                            Id = -34,
                            Name = "Aluminiumunterlegscheiben"
                        },
                        new
                        {
                            Id = -35,
                            Name = "Steinbolzen"
                        },
                        new
                        {
                            Id = -36,
                            Name = "Steinunterlegscheiben"
                        },
                        new
                        {
                            Id = -37,
                            Name = "Plexiglaspumpen"
                        },
                        new
                        {
                            Id = -38,
                            Name = "Titangehäuse"
                        },
                        new
                        {
                            Id = -39,
                            Name = "Steindichtungen"
                        },
                        new
                        {
                            Id = -40,
                            Name = "Bronzeventile"
                        },
                        new
                        {
                            Id = -41,
                            Name = "Textilventile"
                        },
                        new
                        {
                            Id = -42,
                            Name = "Stahlschrauben"
                        },
                        new
                        {
                            Id = -43,
                            Name = "Textilgehäuse"
                        },
                        new
                        {
                            Id = -44,
                            Name = "Aluminiumventile"
                        },
                        new
                        {
                            Id = -45,
                            Name = "Aluminiumventile"
                        },
                        new
                        {
                            Id = -46,
                            Name = "Textilgehäuse"
                        },
                        new
                        {
                            Id = -47,
                            Name = "Plexiglaspumpen"
                        },
                        new
                        {
                            Id = -48,
                            Name = "Bronzebolzen"
                        },
                        new
                        {
                            Id = -49,
                            Name = "Kunststoffriemen"
                        },
                        new
                        {
                            Id = -50,
                            Name = "Steinfilter"
                        },
                        new
                        {
                            Id = -51,
                            Name = "Steinpumpen"
                        },
                        new
                        {
                            Id = -52,
                            Name = "Bronzemuttern"
                        },
                        new
                        {
                            Id = -53,
                            Name = "Acrylkabel"
                        },
                        new
                        {
                            Id = -54,
                            Name = "Acrylsensoren"
                        },
                        new
                        {
                            Id = -55,
                            Name = "Glasriemen"
                        },
                        new
                        {
                            Id = -56,
                            Name = "Keramikpumpen"
                        },
                        new
                        {
                            Id = -57,
                            Name = "Aluminiumbolzen"
                        },
                        new
                        {
                            Id = -58,
                            Name = "Keramikbolzen"
                        },
                        new
                        {
                            Id = -59,
                            Name = "Plexiglasbolzen"
                        },
                        new
                        {
                            Id = -60,
                            Name = "Silberrohre"
                        },
                        new
                        {
                            Id = -61,
                            Name = "Aluminiummuttern"
                        },
                        new
                        {
                            Id = -62,
                            Name = "Acryldichtungen"
                        },
                        new
                        {
                            Id = -63,
                            Name = "Metallmuttern"
                        },
                        new
                        {
                            Id = -64,
                            Name = "Glasventile"
                        },
                        new
                        {
                            Id = -65,
                            Name = "Goldplatten"
                        },
                        new
                        {
                            Id = -66,
                            Name = "Papierfilter"
                        },
                        new
                        {
                            Id = -67,
                            Name = "Textilrohre"
                        },
                        new
                        {
                            Id = -68,
                            Name = "Gummipumpen"
                        },
                        new
                        {
                            Id = -69,
                            Name = "Gummigehäuse"
                        },
                        new
                        {
                            Id = -70,
                            Name = "Goldmuttern"
                        },
                        new
                        {
                            Id = -71,
                            Name = "Steinsensoren"
                        },
                        new
                        {
                            Id = -72,
                            Name = "Keramikfedern"
                        },
                        new
                        {
                            Id = -73,
                            Name = "Silberkabel"
                        },
                        new
                        {
                            Id = -74,
                            Name = "Silberzahnräder"
                        },
                        new
                        {
                            Id = -75,
                            Name = "Titangehäuse"
                        },
                        new
                        {
                            Id = -76,
                            Name = "Keramikunterlegscheiben"
                        },
                        new
                        {
                            Id = -77,
                            Name = "Textilpumpen"
                        },
                        new
                        {
                            Id = -78,
                            Name = "Bronzesensoren"
                        },
                        new
                        {
                            Id = -79,
                            Name = "Keramikriemen"
                        },
                        new
                        {
                            Id = -80,
                            Name = "Silberunterlegscheiben"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("WebEngineering.Areas.Identity.Data.Manager", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("WebEngineering.Areas.Identity.Data.Manager", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebEngineering.Areas.Identity.Data.Manager", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("WebEngineering.Areas.Identity.Data.Manager", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebEngineering.Models.Bestellung", b =>
                {
                    b.HasOne("WebEngineering.Models.Produkt", "Produkt")
                        .WithMany()
                        .HasForeignKey("ProduktId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produkt");
                });

            modelBuilder.Entity("WebEngineering.Models.Lieferung", b =>
                {
                    b.HasOne("WebEngineering.Models.Bestellung", "bestellung")
                        .WithMany()
                        .HasForeignKey("BestellungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebEngineering.Models.Produkt", "Produkt")
                        .WithMany()
                        .HasForeignKey("ProduktId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produkt");

                    b.Navigation("bestellung");
                });
#pragma warning restore 612, 618
        }
    }
}
